# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>

julia_version = "1.10.5"
manifest_format = "2.0"

[[deps.ArangoDB]]
deps = ["Base64", "Dates", "Sockets"]
path = "../ArangoDB.jl"
uuid = "719c9fe8-89eb-588d-a237-0159f38ee2e4"
version = "0.1.0"

[[deps.Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[deps.Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[deps.MaridCodec]]
path = "../MaridCodec.jl"
uuid = "eca7d35b-6611-5bf5-a92e-bc308a796804"
version = "0.1.0"

[[deps.MaridCore]]
deps = ["Dates", "MaridIR", "UUIDs"]
path = "../MaridCore.jl"
uuid = "e7156291-0549-58db-b616-467193d4b712"
version = "0.1.0"

[[deps.MaridGraphQL]]
deps = ["MaridIR"]
path = "../MaridGraphQL.jl"
uuid = "dc948de1-81b6-5b14-aa1c-15a8f36634c8"
version = "0.1.0"

[[deps.MaridIR]]
path = "../MaridIR.jl"
uuid = "0aa8228c-ae90-54ec-b99f-6e73e9362e55"
version = "0.1.0"

[[deps.MaridOpenAPI]]
deps = ["MaridIR"]
path = "../MaridOpenAPI.jl"
uuid = "d46b8009-b507-5415-bdf2-d181fb662532"
version = "0.1.0"

[[deps.MaridRPC]]
deps = ["MaridCore"]
path = "../MaridRPC.jl"
uuid = "6103e3ce-053f-5ec4-9c2b-ebfa0cc52cf7"
version = "0.1.0"

[[deps.MaridStorage]]
deps = ["Dates", "UUIDs"]
path = "../MaridStorage.jl"
uuid = "2f1b9ad7-f130-5c00-9245-1df50bc1442b"
version = "0.1.0"

[[deps.MaridTransport]]
deps = ["Sockets"]
path = "../MaridTransport.jl"
uuid = "9b56d6cb-8332-56b5-a8cb-605b4eec7468"
version = "0.1.0"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[deps.Random]]
deps = ["SHA"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
version = "0.7.0"

[[deps.Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[deps.UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
